# Generated by Django 5.1 on 2024-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_video_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="original_body",
            field=models.TextField(
                blank=True, null=True, verbose_name="Оригинальный текст"
            ),
        ),
    ]
