# Generated by Django 5.1 on 2024-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_comment_original_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="was_edited",
            field=models.BooleanField(default=False),
        ),
    ]
